### ISSUE TITLE
是不是slack的API用不了了？

### ISSUE THREAD

**Issue by Xiao001010** [loveEight/claude#4]
laf日志：

```
Time: 2023-08-24 00:34:25
Request ID: 1b5a67fe-5a6b-4ae9-bc6b-4d4142f3fba4
Function: send-claude
Content:
'An API error occurred: not_authed' 'Error: An API error occurred: not_authed\n' +
  '    at platformErrorFromResult (/app/node_modules/@slack/web-api/dist/errors.js:56:33)\n' +
  '    at WebClient.apiCall (/app/node_modules/@slack/web-api/dist/WebClient.js:181:56)\n' +
  '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
  '    at async Authenticator.newChannel (file:///app/node_modules/claude-api-slack/build/index.js:35:27)\n' +
  '    at async askCluadeAPi (evalmachine.<anonymous>:29:21)\n' +
  '    at async default_1 (evalmachine.<anonymous>:16:12)\n' +
  '    at async FunctionEngine.run (/app/dist/support/function-engine/engine.js:34:24)\n' +
  '    at async CloudFunction.invoke (/app/dist/support/function-engine/function.js:73:23)\n' +
  '    at async handleInvokeFunction (/app/dist/handler/invoke-func.js:59:24)'
```

前端显示：
{"error":"invoke cloud function got error, please check the function logs","requestId":"1b5a67fe-5a6b-4ae9-bc6b-4d4142f3fba4"}

@loveEight

**Comment by CookedMelon** [comment]
I meet this problem too
